-- Up Migration
-- Catalog schema for the curated showcase (sections, wish types, groups, games,
-- store links). Written idempotently so applying it against a database that
-- already holds this data is a safe no-op.

CREATE TABLE IF NOT EXISTS group_sections (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section text
);

CREATE TABLE IF NOT EXISTS wish_types (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text,
  description text
);

CREATE TABLE IF NOT EXISTS gift_groups (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title            text,
  description      text,
  wish_type_id     integer,
  group_section_id integer
);

CREATE TABLE IF NOT EXISTS board_games (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         text,
  group_id      integer,
  cover_image   text,
  instruction   text,
  min_players   integer DEFAULT 0,
  max_players   integer DEFAULT 0,
  video         text,
  in_collection boolean DEFAULT false,
  in_wish_list  boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS links (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link      text,
  currency  text,
  cost      numeric,
  wish_type integer,
  wish_id   integer
);

CREATE INDEX IF NOT EXISTS board_games_group_id_idx ON board_games (group_id);
CREATE INDEX IF NOT EXISTS links_wish_id_idx ON links (wish_id);

-- Down Migration
-- Intentional no-op: the catalog tables may hold the original dataset and are
-- never dropped by a rollback.
SELECT 1;
